name: Run Pytest
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - -y

    - name: Add poetry to path
      run: |
        echo "::set-env name=PATH::$HOME/.poetry/bin:$PATH"

    - name: Install Dependencies
      run: |
        poetry install

    - name: Run Test
      run: |
        poetry run pytest